// Code generated by protoc-gen-go. DO NOT EDIT.
// source: window.proto

/*
Package window is a generated protocol buffer package.

It is generated from these files:
	window.proto

It has these top-level messages:
	SysInfo
	Page
	Msg
	Login
	User
*/
package window

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgEnum int32

const (
	MsgEnum_INFO  MsgEnum = 0
	MsgEnum_WARN  MsgEnum = 1
	MsgEnum_ERROR MsgEnum = 2
	MsgEnum_FATAL MsgEnum = 3
)

var MsgEnum_name = map[int32]string{
	0: "INFO",
	1: "WARN",
	2: "ERROR",
	3: "FATAL",
}
var MsgEnum_value = map[string]int32{
	"INFO":  0,
	"WARN":  1,
	"ERROR": 2,
	"FATAL": 3,
}

func (x MsgEnum) String() string {
	return proto.EnumName(MsgEnum_name, int32(x))
}
func (MsgEnum) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SysInfo struct {
	ServerVersion string `protobuf:"bytes,1,opt,name=serverVersion" json:"serverVersion,omitempty"`
	UserNum       uint32 `protobuf:"varint,2,opt,name=userNum" json:"userNum,omitempty"`
	TimeStamp     int64  `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
}

func (m *SysInfo) Reset()                    { *m = SysInfo{} }
func (m *SysInfo) String() string            { return proto.CompactTextString(m) }
func (*SysInfo) ProtoMessage()               {}
func (*SysInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SysInfo) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

func (m *SysInfo) GetUserNum() uint32 {
	if m != nil {
		return m.UserNum
	}
	return 0
}

func (m *SysInfo) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

type Page struct {
	Page string `protobuf:"bytes,1,opt,name=page" json:"page,omitempty"`
	Msg  *Msg   `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *Page) Reset()                    { *m = Page{} }
func (m *Page) String() string            { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()               {}
func (*Page) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Page) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *Page) GetMsg() *Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Msg struct {
	Type MsgEnum `protobuf:"varint,1,opt,name=type,enum=window.MsgEnum" json:"type,omitempty"`
	Text string  `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *Msg) Reset()                    { *m = Msg{} }
func (m *Msg) String() string            { return proto.CompactTextString(m) }
func (*Msg) ProtoMessage()               {}
func (*Msg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Msg) GetType() MsgEnum {
	if m != nil {
		return m.Type
	}
	return MsgEnum_INFO
}

func (m *Msg) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Login struct {
	Phone    string `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	UserNum  uint32 `protobuf:"varint,3,opt,name=userNum" json:"userNum,omitempty"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Login) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Login) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Login) GetUserNum() uint32 {
	if m != nil {
		return m.UserNum
	}
	return 0
}

type User struct {
	Num        uint32 `protobuf:"varint,1,opt,name=num" json:"num,omitempty"`
	Phone      string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	Password   []byte `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Name       string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	LastRemote string `protobuf:"bytes,5,opt,name=lastRemote" json:"lastRemote,omitempty"`
	LastLogin  int64  `protobuf:"varint,6,opt,name=lastLogin" json:"lastLogin,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *User) GetNum() uint32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetLastRemote() string {
	if m != nil {
		return m.LastRemote
	}
	return ""
}

func (m *User) GetLastLogin() int64 {
	if m != nil {
		return m.LastLogin
	}
	return 0
}

func init() {
	proto.RegisterType((*SysInfo)(nil), "window.SysInfo")
	proto.RegisterType((*Page)(nil), "window.Page")
	proto.RegisterType((*Msg)(nil), "window.Msg")
	proto.RegisterType((*Login)(nil), "window.Login")
	proto.RegisterType((*User)(nil), "window.User")
	proto.RegisterEnum("window.MsgEnum", MsgEnum_name, MsgEnum_value)
}

func init() { proto.RegisterFile("window.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0xdd, 0x90, 0x04, 0xc8, 0x00, 0xbb, 0xd1, 0x68, 0x0f, 0xd1, 0x6a, 0x5b, 0xa1, 0xb4, 0x07,
	0xd4, 0x03, 0x07, 0x38, 0xf5, 0x52, 0x89, 0x03, 0x48, 0x48, 0x7c, 0x54, 0xa6, 0x1f, 0xe7, 0x54,
	0xb8, 0x69, 0xa4, 0xda, 0x8e, 0x6c, 0xa7, 0x94, 0xff, 0xd2, 0x1f, 0x5b, 0xd9, 0x09, 0x10, 0x0e,
	0xbd, 0xbd, 0xf7, 0xc6, 0xf3, 0xde, 0xcc, 0xc8, 0xd0, 0xdd, 0x65, 0x7c, 0x2b, 0x76, 0xc3, 0x5c,
	0x0a, 0x2d, 0xb0, 0x59, 0xb2, 0x38, 0x85, 0xd6, 0x66, 0xaf, 0xe6, 0xfc, 0x55, 0xe0, 0x35, 0xf4,
	0x14, 0x95, 0x1f, 0x54, 0x3e, 0x51, 0xa9, 0x32, 0xc1, 0x23, 0xa7, 0xef, 0x0c, 0x02, 0x72, 0x2e,
	0x62, 0x04, 0xad, 0x42, 0x51, 0xb9, 0x2a, 0x58, 0xd4, 0xe8, 0x3b, 0x83, 0x1e, 0x39, 0x50, 0xfc,
	0x0f, 0x81, 0xce, 0x18, 0xdd, 0xe8, 0x84, 0xe5, 0x91, 0xdb, 0x77, 0x06, 0x2e, 0x39, 0x09, 0xf1,
	0x2d, 0x78, 0xf7, 0x49, 0x4a, 0x11, 0xc1, 0xcb, 0x93, 0x94, 0x56, 0xe6, 0x16, 0xe3, 0x05, 0xb8,
	0x4c, 0xa5, 0xd6, 0xaf, 0x33, 0xea, 0x0c, 0xab, 0x41, 0x97, 0x2a, 0x25, 0x46, 0x8f, 0xef, 0xc0,
	0x5d, 0xaa, 0x14, 0xaf, 0xc0, 0xd3, 0xfb, 0xbc, 0xec, 0xfc, 0x3d, 0xfa, 0x53, 0x7b, 0x36, 0xe5,
	0x05, 0x23, 0xb6, 0x68, 0xec, 0x35, 0xfd, 0xd4, 0xd6, 0x2b, 0x20, 0x16, 0xc7, 0x1b, 0xf0, 0x17,
	0x22, 0xcd, 0x38, 0xfe, 0x05, 0x3f, 0x7f, 0x13, 0xfc, 0x10, 0x5e, 0x12, 0xfc, 0x07, 0xed, 0x3c,
	0x51, 0x6a, 0x27, 0xe4, 0xb6, 0x6a, 0x3b, 0xf2, 0xfa, 0xb6, 0xee, 0xd9, 0xb6, 0xf1, 0x97, 0x03,
	0xde, 0xa3, 0xa2, 0x12, 0x43, 0x70, 0x79, 0xc1, 0xac, 0x65, 0x8f, 0x18, 0x78, 0x8a, 0x69, 0xfc,
	0x14, 0x63, 0xbc, 0xba, 0xb5, 0x18, 0x04, 0x8f, 0x27, 0x8c, 0x46, 0x5e, 0x39, 0xb5, 0xc1, 0x78,
	0x09, 0xf0, 0x9e, 0x28, 0x4d, 0x28, 0x13, 0x9a, 0x46, 0xbe, 0xad, 0xd4, 0x14, 0x73, 0x6e, 0xc3,
	0xec, 0x66, 0x51, 0xb3, 0x3c, 0xf7, 0x51, 0xb8, 0x19, 0x43, 0xab, 0x3a, 0x0c, 0xb6, 0xc1, 0x9b,
	0xaf, 0x66, 0xeb, 0xf0, 0x97, 0x41, 0xcf, 0x13, 0xb2, 0x0a, 0x1d, 0x0c, 0xc0, 0x9f, 0x12, 0xb2,
	0x26, 0x61, 0xc3, 0xc0, 0xd9, 0xe4, 0x61, 0xb2, 0x08, 0xdd, 0x97, 0xa6, 0xfd, 0x1b, 0xe3, 0xef,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0xf1, 0x9e, 0xaa, 0x2b, 0x02, 0x00, 0x00,
}
